name: Build and Release Data Pack

on:
  push:
    tags:
      - "release/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Project
        uses: actions/checkout@v4

      - name: Build and Test
        run: |
          . build.sh
          [ -f ${PWD##*/}.zip ]

      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Assets
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: '*.zip'
